---
format: html
subtitle: 'UCID: anticip_regret_79n2w1bj'
title: Anticipated regret
toc: true
---

## Definition

Anticipated regret is the expectation that the decision to perform or not perform a certain behaviour will result in disappointment.





## Developing Measurement Instruments

Anticipated regret stems from the the expectation that the decision to perform or not perform the target behaviour will lead to feelings of regret. Therefore, anticipated regret with regard to the target behaviour is assessed via the subconstruct action regret (dct:action_regret_79n2w1bj) and inaction regret (dct:inaction_regret_79n2r0t0).

Whether assessment of action regret or inaction regret, or both, is more appropriate depends on the target behaviour and setting of the study. For example, if the target behaviour is "exercising at least six times over the next two weeks", then measuring inaction regret appears more logical: "If you would not exercise at least six times in the next two weeks, how much regret would you feel?", with anchors "none" (=0) and "a lot" (=4). However, one can imagine situations (e.g. exercise as escapism, recovery from injury) in which it makes sense to also measure in the opposite direction (i.e. assess action regret): "If you would exercise at least six times in the next two weeks, how much regret would you feel?".

Expressed as a numeric score, the level of anticipated regret is equal to the level of action or inaction regret, if only one of the two subconstructs is assessed. When both the level of action and inaction regret are measured (with regard to the same target behaviour), the situation is different. In that case, people that experience anticipated regret tend to have a high score on either action or inaction regret. Therefore, calculating a sum or mean score for the two measures combined does not make sense, as this would make the scores of people with a strong experience of anticipated regret (e.g. 4+0=4 sumscore) equal to people with a moderate experience of anticipated regret (e.g. 2+2=4 sumscore), which would no do justice to their experience. Furthermore, it seems likely that for the former group, the instigation towards action/inaction with respect to the target behaviour is greater, precisely because in this group anticipated regret is experienced stronger. Creating a sum or average score from action and inaction regret scores thus does not make sense, neither to express the level of experienced anticipated regret nor to predict engagement vs non-engagement in the target behaviour. 

Substracting one score from the other, or multiplying scores, does not help with the interpretation either. Therefore, no combined score is created from action and inaction regret and scores for both subcontructs are independently assessed and interpreted.

For anticipated regret expressed as a composite score (i.e. the summation of action and inaction regret scores) see dct:anticip_regret_79n2w1bh

## Coding Measurement Instruments

Questions or questionnaires that measure the expectation that enagement or non-engagement in the target behaviour will lead to feelings of regret. In most research, it is not specified whether the questions used measure action or inaction regret (the two forms in which anticipated regret may appear), and thus (if of interest) has to be deduced from the formulation of the questions. In most cases either action or inaction regret is used. Which one of the two is used, is mostly guided by the target behaviour. 

For example in the study "Deciding to exercise: The role of anticipated regret" (Abraham & Sheeran, 2004), the target behaviour is "exercising at least six times over the next two weeks", and the two items measuring anticipated regret both assess action regret (although the authors do no mention such a specification): "If I did not exercise at least six times in the next two weeks, I would feel regret" and "‘If I did not exercise at least six times in the next two weeks, I would feel upset’, witch anchors "definitely no" and "definitely yes" for both items.

## Eliciting Construct Content (Qualitative Research)

Conduct a qualitative study where participants are interviewed, and the interviews are either recorded and transcribed, or notes are kept. These sources are then coded using the instruction for aspect coding.

In this qualitative study, use one of the following two pairs of questions: ‘What do you expect to feel after engaging in TARGET BEHAVIOUR?' and ‘What do you expect to feel after not engaging in TARGET BEHAVIOUR?'; or: 'What emotions do do you expect to experience after engaging in TARGET BEHAVIOUR?' and 'What emotions do do you expect to experience after not engaging in TARGET BEHAVIOUR?'

## Coding Qualitative Data

Expressions that demonstrate or imply that one expects to experience feelings of regret if one would engage/not engage in the target behaviour, usings verbs such as 'remorse', 'sorry', and 'lament'.


