---
format: html
subtitle: 'UCID: capacity_belief_73dnt600'
title: Capacity belief
toc: true
---

## Definition


A person's belief about the degree to which he/she can, is able to, or is capable of performing a particular behavior.

## Developing Measurement Instruments

The measurement of capacity beliefs starts with an elicitation study to identify the content of capacity beliefs about the behaviour which are shared by the target population. 

To obtain quantitative data regarding capacity beliefs, the participant is subsequently asked to respond to two questions with respect to each salient capacity belief, one question to assess the perceived likelihood that the capacity will be present (see dct:capacity_subskillPresence_73dnt5zy), and the other to measure the perceived importance of the capacity to facilitate or impede behavioral performance (see dct:capacity_subskillImportance_73dnt5zz).

Finally, to get a total quantitative score of a capacity belief, the perceived presence of a capacity is multiplied by its perceived importance. The total score of a capacity belief enables the assessment of the importance of the contribution of a capacity belief, in comparison with other capacity beliefs, to the capacity beliefs composite (see dct:capacity_belCom_73dnt601).  


## Coding Measurement Instruments

Each capacity belief is the product term of the multiplication of the perceived presence of a capacity (i.e. 'subskill') (see dct:capacity_subskillPresence_73dnt5zy) by its perceived importance (see dct:capacity_subskillImportance_73dnt5zz). 

Therefore, whether an capacity belief exerts influence (and if so, to what extent) on the capacity beliefs composite (see dct:capacity_belCom_73dnt601), and whether a particular capacity belief lowers or increases the sense of perceived capacity, can only be deduced by concurrent consultation of the two subcomponents of which it is constructed. Table 5.5 on p. 171 of the Reasoned Action Approach (RAA) book (Ajzen & Fishbein, 2010) provides an example how the subcomponents exert an influence on individual control beliefs (in Table 5.5 it concerns autonomy beliefs).

## Eliciting Construct Content (Qualitative Research)

Capacity beliefs can not be directly elicited. They are the product of the multiplication of perceived subskill presence (dct:capacity_subskillPresence_73dnt5zy) by the perceived  importance of this subskill (dct:capacity_subskillImportance_73dnt5zz). See these two subconstructs for instructions for eliciting their respective construct content.



## Coding Qualitative Data

Capacity beliefs can not be directly elicited. They are the product of the multiplication of perceived subskill presence (dct:capacity_subskillPresence_73dnt5zy) by the perceived  importance of this subskill (dct:capacity_subskillImportance_73dnt5zz). See these two subconstructs for instructions for coding their respective construct content.



