---
format: html
subtitle: 'UCID: descrNorms_belief_73dnt5zm'
title: Descriptive norm belief
toc: true
---

## Definition

A person's belief that important individuals or groups in his/her life perform or don’t perform a particular behavior.

## Developing Measurement Instruments

The measurement of descriptive norm beliefs starts with an elicitation study to identify the content of descriptive norm beliefs about the behaviour which are shared by the target population. 

To obtain quantitative data regarding descriptive norm beliefs, the participant is subsequently asked to respond to two questions with respect to each salient descriptive norm belief, one to assess the perceived behaviour of a given social referent (dct:referentBehavior_73dnt5zk) and the other to measure the identification with that social referent  (dct:referentIdentification_73dnt5zl). 

Finally, to get a total quantitative score of a descriptive norm belief, the perceived behaviour of a social referent is multiplied by the identification with that social referent . The total score of a descriptive norm belief enables the assessment of the importance of the contribution of a descriptive norm belief, in comparison with other descriptive norm beliefs, to the descriptive norm beliefs composite (dct:descrNorms_belCom_73dnt5zn).


## Coding Measurement Instruments

Each descriptive norm belief is the product term of the multiplication of the perceived behaviour of a given social referent (dct:referentBehavior_73dnt5zk) by the identification with that social referent  (dct:referentIdentification_73dnt5zl).  

Therefore, whether an descriptive norm belief exerts influence (and if so, to what extent) on the descriptive norm beliefs composite (dct:descrNorms_belCom_73dnt5zn), and whether a particular descriptive norm belief lowers or increases the perception that salient normative referents are performing the behaviour in question, can only be deduced by concurrent consultation of the two subcomponents of which it is constructed. Table 4.1 on p. 136 of the Reasoned Action Approach book (Ajzen & Fishbein, 2010)  provides an example how the subcomponents exert an influence on individual normative beliefs (in Table 4.1 it concerns injunctive normative beliefs).


## Eliciting Construct Content (Qualitative Research)

Descriptive norm beliefs can not be directly elicited. They are the product of a participant's perception of a normative referent's conduct of the target behaviour multiplied by the degree a participant wants to be like that normative referent with regards to the target behaviour

See these two subconstructs  (i.e. dct:referentBehavior_73dnt5zk and dct:referentIdentification_73dnt5zl) for instructions for eliciting their respective construct content.


## Coding Qualitative Data

Descriptive norm beliefs can not be directly elicited. They are the product of a participant's perception of a normative referent's conduct of the target behaviour multiplied by the degree a participant wants to be like that normative referent with regards to the target behaviour

See these two subconstructs  (i.e. dct:referentBehavior_73dnt5zk and dct:referentIdentification_73dnt5zl) for instructions for coding their respective construct content.


