---
format: html
subtitle: 'UCID: identifiedBehaviour_79n2r0t0'
title: Identified regulation of behaviour
toc: true
---

## Definition

In identified regulation a person endorses or identifies with the value or importance of a behaviour or health practice.


## Developing Measurement Instruments

Use Likert scales that measure the degree to which engagement in the target activity is controlled by identified regulation.

The Situational Motivation Scale (SIMS) (Guay et al., 2000) is a frequently used self-report instrument to assess identified regulation of behaviour. Beside identified regulation of behaviour, the SIMS assesses intrinsic regulation, external regulation, and amotivation, and is used to assess motivation for various activities (e.g. physical exercise, academic performance). 

The SIMS asks participants “Why are you currently engaged in this activity?”. Scale items represent potential answers to this question. Responses are given on a 7-point Likert scale ranging from "Does not correspond at all" to "Corresponds exactly".

Examples of statements expressing identified regulation of behaviour are: "Because I am doing it for my own good", "Because I think this activity is good for me", and "Because I believe this activity is important for me".

## Coding Measurement Instruments

Instruments that measure the degree to which engagement in the target activity is controlled by identified regulation.

The Situational Motivation Scale (SIMS) (Guay et al., 2000) is a frequently used self-report instrument to assess identified regulation of behaviour. Beside identified regulation of behaviour, the SIMDS assesses intrinsic regulation, external regulation, and amotivation, and is used to assess motivation for various activities (e.g. physical exercise, academic performance). 

The SIMS asks participants “Why are you currently engaged in this activity?”. Scale items represent potential answers to this question. Responses are given on a 7-point Likert scale ranging from "Does not correspond at all" to "Corresponds exactly".

Examples of statements expressing  identified regulation of behaviour are: "Because I am doing it for my own good", "Because I think this activity is good for me", and "Because I believe this activity is important for me".

## Eliciting Construct Content (Qualitative Research)

Conduct a qualitative study where participants are interviewed, and the interviews are either recorded and transcribed, or notes are kept. These sources are then coded using the instruction for aspect coding.

In this qualitative study, use this question: “Why are you currently engaged in TARGET BEHAVIOUR?” 

For example: "Why do you currently wear ear plugs at concerts?" or "Why do you currently follow a calorie-restricted diet?"

## Coding Qualitative Data

Expressions that demonstrate or imply that engagement in the target behaviour is controlled by identified regulation, using phrases such as "Because I am doing it for my own good" and "Because I believe this activity is important for me".

Expressions that demonstrate or imply the presence of externally regulated behaviour should be coded as dct:extBehaviour_79n2r0sz.

Expressions that demonstrate or imply the presence of introjected regulation of behaviour should be coded as dct:introjBehaviour_79n2r0t0.

Expressions that demonstrate or imply the presence of integrated regulation of behaviour should be coded as dct:integratedBehaviour_79n2r0t0.

In practice, it can be difficult to distinguish expressions belonging to the four types of extrinsic motivation (external, introjected, identified, and integrated self-regulation). Therefore, a less precise categorization can be made between controlled and autonomous motivation. External and introjected regulation belonging to the first category, and identified and integrated self-regulation belonging to the first category. When this dichotomous categorization of extrinsic motivation is maintained, expressions typical of identified and integrated self-regulation can be grouped together.

Expressions that demonstrate or imply the presence of intrinsic regulation of behaviour should be coded as dct:intrinsicBehaviour_79n2r0t0.

Expressions that demonstrate or imply the absence of motivation to engage in the target behaviour (i.e. "amotivation") should be coded as dct:motivation_79n2fh4q, and in a supplementary comment scored "0" or "absent".

Expressions that refer to the presence of motivation with regard to the target behaviour without specifying the nature of its regulation or expressions that refer to the presence of motivation in general should be coded dct:motivation_79n2fh4q.

