---
format: html
subtitle: 'UCID: impulse_79n2r0t0'
title: Impulse
toc: true
---

## Definition

An impulsive action is defined as a non-deliberate action that serves the purpose of rendering one’s relation to the object, event, or state of the world more pleasant or less unpleasant.


## Developing Measurement Instruments

To measure impulsive action in humans, several tests exist in which participants have to carry out an assignment or a series of assignments; among these tests the go-no go task, stop signal task (SST), Stroop task, and the continuous performance task (CPT) are most often utilized.

In addition, self-report instruments are used to measure impulsive choice and/or impulsive action, of which the Barratt Impulsiveness Scale (BIS-11) is most commonly used. The BIS-11 consists of 30 items, and answers on each item are measured on a 4-point scale (rarely/never, occasionally, often, almost always), with higher scores indicative of greater impulsivity. Examples of items used are: "I act on the spur of the moment" and " I say things without thinking".

The aforementioned tests measure impulsive action as a general trait, not related to specific behaviours or objects. If one wants to assess impulsivity with regard to a particular behaviour or object, specific questions can be composed that measure the frequency impulses are experienced, and/or the strength of these impulses, in situations related to the target behaviour/object.

To measure impulsivity related to a specific behaviour, the stem "When it comes to TARGET BEHAVIOUR...." can be composed, followed by a series of phrases that express behaviour considered indicative for the presence or absence of impulsivity. For example: "When it comes to smoking cigarettes... 1) I do it without thinking about it; 2) I am self controlled; 3) I don't manage to plan my behaviour 4) I act on the spur of the moment 5) I often suddenly abandon my behavioural intentions. Responses on these items can be given on a 5-point Likert scale ranging from "totally agree" to "totally disagree".

Alternatively, a series of unique items can be composed to measure behaviour- or object-related impulsivity, such as: "I don't wear ear plugs because when I decide to go to an event or concert it's on the spur of the moment" (for target behaviour "wearing ear plugs when exposed to loud music") and "When I hear a good track, I just have to turn off the volume restriction" (for target behaviour "use volume restriction on music players") with responses "totally agree" and "totally disagree" as anchors on a 5-point Likert scale.

Impulsivity can be regarded as the converse of self-control. Therefore, the same instrument to assess self control (dct:self_control_79n2fh4t) can potentially be used to measure impulsivity. However, the scoring for the questionnaire items should be reversed (see dct:self_control_79n2fh4t for an example).


## Coding Measurement Instruments

Questions or questionnaires that measure impulsivity related to a specific behaviour or object. For self-report asessment, a statement such as "When it comes to TARGET BEHAVIOUR...." can be composed, followed by a series of phrases that express behaviour considered indicative for the presence or absence of impulsivity. For example: "When it comes to smoking cigarettes... 1) I do it without thinking about it; 2) I am self controlled; 3) I don't manage to plan my behaviour; 4) I act on the spur of the moment; 5) I often suddenly abandon my behavioural intentions; 6) I afterwards frequently regret that I smoked. Responses on these items can be given on a 5-point Likert scale ranging from "totally agree" to "totally disagree".

Alternatively, unique items can be created to measure behaviour- or object-related impulsivity, such as: "When I hear a good track, I just have to turn off the volume restriction" (for target behaviour "use volume restriction on music players") with responses "totally agree" and "totally disagree" as anchors on a 5-point Likert scale. 

Beside behaviour- or object-related impulsivity, impulsivity as a trait can be measured. The Barratt Impulsiveness Scale (BIS-11) is the most commonly used self-report questionnaire for this pupose. Furthermore, numerous tests exist in which participants have to carry out an assignment or a series of assignments; among these tests the go-no go task, stop signal task (SST), Stroop task, and the continuous performance task (CPT)  are most often utilized.

Impulsivity can be regarded as the converse of self-control. Therefore, the same instrument to assess self control (see dct:self_control_XXX) can potentially be used to measure impulsivity. However, the scoring for the questionnaire items should be reversed (see dct:self_control_XXX for an example).

## Eliciting Construct Content (Qualitative Research)

Conduct a qualitative study where participants are interviewed, and the interviews are either recorded and transcribed, or notes are kept. These sources are then coded using the instruction for aspect coding.

In this qualitative study, use these two questions (with preferably some questions in between): "When it comes to TARGET BEHAVIOUR how deliberate and controlled do you see your actions?" and "When it comes to TARGET BEHAVIOUR how spontaneous do you see your actions?".

These same questions are used to elicite expressions indicative of self-control (see dct:self_control_XXX).

In addition, for the assessment of clinical levels of impulsivity in adults (e.g. in Attention Deficit Disorder), (semi) structured interview instruments exist such as the ACE+ (Young, 2016) and the MIDI (Grant, 2008).




## Coding Qualitative Data

Expressions that demonstrate or imply the presence or absence of impulsivity. In the context of behaviour change interventions (i.e. health behaviour changes), this impulsivity is regarded with respect to a specific behaviour or object. Trait impulsivity, i.e. impulsivity across situations, not specifically linked to a particular behaviour or object, is usually not the focus of interest. Therefore, expressions indicative of impulsivity should be coded as such only when they concern the behaviour or object of interest, unless beforehand another decision has been made. Expressions indicative of the presence of impulsivity may contain words such as "unplanned", "undeliberate", and "on the spur of the moment". 

Expressions indicative of self-control (e.g. ""I sticked to my plan, in spite of all these temptations") should be coded as dct:self_control_79n2fh4t.

Expressions that describe situations or circumstances that evoke a desire to engage in the target behaviour (e.g. "When I see somebody drink a beer it is impossible to resist") should be coded as dct:tempation_79n2fh4w.

