---
format: html
subtitle: 'UCID: instrAttitude_belief_73dnt5z8'
title: Instrumental attitude belief
toc: true
---

## Definition

Beliefs are defined as the subjective probability that an object has a certain attribute, where ‘object’ and ‘attribute’ are used in the generic sense, and refer to any discriminable aspect of an individual’s world. Conform the expectancy-value model of attitude, beliefs are the product of the expectation that engaging in a behavior will have a given consequence and the evaluation of that consequence as (very) negative or (very) positive. Instrumental attitude beliefs concern beliefs about consequences of engaging in the behavior for achieving one’s goals.


## Developing Measurement Instruments

Instrumental attitude beliefs are measured by measuring both of the component constructs, i.e.: dct:instrAttitude_evaluation_73dnt5z7 and dct:instrAttitude_expectation_73dnt5z6.


## Coding Measurement Instruments

Each instrumental attitude belief is the product term of the multiplication of the evaluation of the perceived  instrumentall consequences of the target behaviour (dct:instrAttitude_evaluation_73dnt5z7) by the perceived likelihood that engaging in the behaviour will actually have these consequences (dct:instrAttitude_expectation_73dnt5z6).

Therefore, whether an  instrumental attitude belief exerts influence (and if so, to what extent) on the instrumental attitude beliefs composite (dct:instrAttitude_belCom_73dnt5z9), and whether a particular instrumental attitude belief leads to a more favourable or more unfavourable instrumental attitude towards performing the target behaviour, can only be deduced by concurrent consultation of the two subcomponents of which it is constructed. Table 3.2 on p. 98 of  the Reasoned Action Approach book (Ajzen & Fishbein, 2010) illustrates how the two subcomponents can exert an influence on individual attitude beliefs.


## Eliciting Construct Content (Qualitative Research)

Instrumental attitude beliefs can not be directly elicited. They are the product of the expected instrumental consequences of a target behaviour (instrAttitude_expectation_73dnt5z6) multiplied by the evaluation of those consequences (instrAttitude_evaluation_73dnt5z7). 

See these two subconstructs for instructions for eliciting their respective construct content.


## Coding Qualitative Data

Instrumental attitude beliefs can not be directly elicited. They are the product of the expected instrumental consequences of a target behaviour (instrAttitude_expectation_73dnt5z6) multiplied by the evaluation of those consequences (instrAttitude_evaluation_73dnt5z7). 

See these two subconstructs for instructions for coding their respective construct content.


