---
format: html
subtitle: 'UCID: integratedBehaviour_79n2r0t0'
title: Integrated regulation of behaviour
toc: true
---

## Definition

In integrated regulation a person not only values a behaviour, but has also aligned it with other central values and lifestyle patterns.

## Developing Measurement Instruments

Use Likert scales that measure the degree to which participants' engagement in the target activity is determined by integrated regulation. Examples of statements expressing integrated regulation of behaviour are: "It is essential to my identity and sense of self", "It is genuinely part of me", "It is consistent with my values, goals and aims in life", and "Doing TARGET BEHAVIOUR and being myself are inseparable". Responses on these items are given on a 4-point scale  ranging from "Not true at  all" to "Very true". These sample items are form the Integrated regulation (INTEG) scale developed by McLachlan, Spray, and Hagger (2011) which assesses integrated regulation in exercise behaviour.

The frequently used Situational Motivation Scale (SIMS) (Guay et al., 2000) does not measure  integrated (nor introjected) regulation. The SIMS assesses self-reported intrinsic regulation, identified regulation, external regulation, and amotivation, and is used to assess motivation for various activities (e.g. physical exercise, academic performance). 

In practice, it is difficult to distinguish the four types of extrinsic motivation (external, introjected, identified, and integrated self-regulation) using self-report instruments (i.e. insufficient discriminant validity). Therefore, a less precise categorization can be made between controlled and autonomous motivation. External and introjected regulation belonging to the first category, and identified and integrated self-regulation belonging to the first category. When this dichotomous categorization of extrinsic motivation is maintained, items to assess identified and integrated self-regulation can be grouped together.



## Coding Measurement Instruments

Instruments that measure the degree to which participants' engagement in the target activity is determined by integrated regulation. Examples of statements expressing integrated regulation of behaviour are: "It is essential to my identity and sense of self", "It is genuinely part of me", "It is consistent with my values, goals and aims in life", and "Doing TARGET BEHAVIOUR and being myself are inseparable". Responses on these items are given on a 4-point scale  ranging from "Not true at  all" to "Very true". These sample items are form the Integrated regulation (INTEG) scale developed by McLachlan, Spray, and Hagger (2011) which assesses integrated regulation in exercise behaviour.

The frequently used Situational Motivation Scale (SIMS) (Guay et al., 2000) does not measure  integrated (nor introjected) regulation. The SIMS assesses self-reported intrinsic regulation, identified regulation, external regulation, and amotivation, and is used to assess motivation for various activities (e.g. physical exercise, academic performance). 

In practice, it is difficult to distinguish the four types of extrinsic motivation (external, introjected, identified, and integrated self-regulation) using self-report instruments (i.e. insufficient discriminant validity). Therefore, a less precise categorization can be made between controlled and autonomous motivation. External and introjected regulation belonging to the first category, and identified and integrated self-regulation belonging to the first category. When this dichotomous categorization of extrinsic motivation is maintained, items to assess identified and integrated self-regulation can be grouped together.



## Eliciting Construct Content (Qualitative Research)

Conduct a qualitative study where participants are interviewed, and the interviews are either recorded and transcribed, or notes are kept. These sources are then coded using the instruction for aspect coding.

In this qualitative study, use this question: “Why are you currently engaged in TARGET BEHAVIOUR?” 

For example: "Why do you currently wear ear plugs at concerts?" or "Why do you currently follow a calorie-restricted diet?"

## Coding Qualitative Data

Expressions that demonstrate or imply that engagement in the target behaviour is determined by integrated regulation, using phrases such as "It is genuinely part of me", "It is consistent with my values, goals and aims in life", and "Doing TARGET BEHAVIOUR and being myself are inseparable".

Expressions that demonstrate or imply the presence of externally regulated behaviour should be coded as dct:extBehaviour_79n2r0sz.

Expressions that demonstrate or imply the presence of identified regulation of behaviour should be coded as dct:identifiedBehaviour_79n2r0t0.

Expressions that demonstrate or imply the presence of introjected regulation of behaviour should be coded as dct:introjBehaviour_79n2r0t0.

In practice, it can be difficult to distinguish expressions belonging to the four types of extrinsic motivation (external, introjected, identified, and integrated self-regulation). Therefore, a less precise categorization can be made between controlled and autonomous motivation. External and introjected regulation belonging to the first category, and identified and integrated self-regulation belonging to the first category. When this dichotomous categorization of extrinsic motivation is maintained, expressions typical of identified and integrated self-regulation can be grouped together.

Expressions that demonstrate or imply the presence of intrinsically regulated behaviour should be coded as dct:intrinsicBehaviour_79n2r0t0.

Expressions that demonstrate or imply the absence of motivation to engage in the target behaviour (i.e. "amotivation") should be coded as dct:motivation_79n2fh4q, and in a supplementary comment scored "0" or "absent".

Expressions that refer to the presence of motivation with regard to the target behaviour without specifying the nature of its regulation or expressions that refer to the presence of motivation in general should be coded dct:motivation_79n2fh4q.

