---
format: html
subtitle: 'UCID: need_79n2fh4r'
title: Need satisfaction
toc: true
---

## Definition

An individual's perception whether an activity or situation satisfies an universal human need ( i.e. what is considered essential or necessary for well-being and healthy functioning).






## Developing Measurement Instruments

Numerous self-report instruments exist to measure need satisfaction. These instruments measure the degree needs are satisfied in a particular domain (e.g. work, relationship), the degree needs are satisfied by a particular activity (e.g. a certain type of sports), or they assess need satisfaction in general.

Instruments that measure need satisfaction most often assume that humans have universal needs. In particular, Self-Determination Theory (SDT) (Deci & Ryan, 1985) and Maslow's (1968) Hierarchy of Needs have instigated the development of instruments to measure the satisfaction of these universal needs. The Basic Psychological Needs Scale (BPNS) (Gagné et al., 2003) and the Balanced Measure of Psychological Needs (BMPN) (Sheldon et al., 2012) measure needs from a SDT-perspective, while the Basic Need Satisfaction Inventory (BNSI) (Leidy et al., 1994)) adopts Maslow's standpoint on human needs.

For behaviour change (e.g. instigating healthy lifestyle choices), measuring general, as well as measuring domain- or activity-specific need satisfaction may have its merits. For example, Timmerman et al. (2001) found that the lower the level of basic need satisfaction, the more likely one is engaged in emotional eating. Need satisfaction at this general level, however, is harder to change than needs being met by specific activities or in a narrow domain. Therefore, instruments pertaining to the latter category are preferably used.

Need satisfaction can be asssessed by following a series of four steps: Firstly, depending on the theoretical background one adheres to (e.g. SDT) a list of of universal needs is composed. Secondly, to measure whether these needs are met by the situation or activity of interest, for each of these needs a number of items are used to assess the level of needs satisfaction. Thirdly, the item sumscores for each need, and the overall sumcore of all needs together are calculated. Fourth, the degree individual needs and all need together are satisfied by an activity or situation can be deduced from the two sumscores. 

Need satisfaction in a particular domain can, for example, be assessed with the following sample items. These sample items pertain to the assessment of need satisfaction at work but (with slight adjustments) could also be used to measure need satisfaction in other domains or concerning specific activities. Participants are asked to indicate how true each statement is for them, with answer option ranging from "Not at all true" to "Very true" on a 7-point Likert scale: "I feel like I can make a lot of inputs to deciding how my job gets done", "People at work care about me", and "Most days I feel a sense of accomplishment from working". These three items reflect what SDT regards as the three basic human needs: autonomy, relatedness, and competence.



## Coding Measurement Instruments

Numerous self-report instruments exist to measure need satisfaction. These instruments measure the degree needs are satisfied in a particular domain (e.g. work, relationship), the degree needs are satisfied by a particular activity (e.g. a certain type of sports), or they assess need satisfaction in general.

Instruments that measure need satisfaction most often assume that humans have universal needs. In particular, Self-Determination Theory (SDT) (Deci & Ryan, 1985) and Maslow's (1968) Hierarchy of Needs have instigated the development of instruments to measure the satisfaction of these universal needs. The Basic Psychological Needs Scale (BPNS) (Gagné et al., 2003) and the Balanced Measure of Psychological Needs (BMPN) (Sheldon et al., 2012) measure needs from a SDT-perspective, while the Basic Need Satisfaction Inventory (BNSI) (Leidy et al., 1994)) adopts Maslow's standpoint on human needs.

For behaviour change (e.g. instigating healthy lifestyle choices), measuring general, as well as measuring domain- or activity-specific need satisfaction may have its merits. For example, Timmerman et al. (2001) found that the lower the level of basic need satisfaction, the more likely one is engaged in emotional eating. Need satisfaction at this general level, however, is harder to change than needs being met by specific activities or in a narrow domain. Therefore, instruments pertaining to the latter category are preferably used.

Need satisfaction can be asssessed by following a series of four steps: Firstly, depending on the theoretical background one adheres to (e.g. SDT) a list of of universal needs is composed. Secondly, to measure whether these needs are met by the situation or activity of interest, for each of these needs a number of items are used to assess the level of needs satisfaction. Thirdly, the item sumscores for each need, and the overall sumcore of all needs together are calculated. Fourth, the degree individual needs and all need together are satisfied by an activity or situation can be deduced from the two sumscores. 

Need satisfaction in a particular domain can, for example, be assessed with the following sample items. These sample items pertain to the assessment of need satisfaction at work but (with slight adjustments) could also be used to measure need satisfaction in other domains or concerning specific activities. Participants are asked to indicate how true each statement is for them, with answer option ranging from "Not at all true" to "Very true" on a 7-point Likert scale: "I feel like I can make a lot of inputs to deciding how my job gets done", "People at work care about me", and "Most days I feel a sense of accomplishment from working". These three items reflect what SDT regards as the three basic human needs: autonomy, relatedness, and competence.


## Eliciting Construct Content (Qualitative Research)

Conduct a qualitative study where participants are interviewed, and the interviews are either recorded and transcribed, or notes are kept. These sources are then coded using the instruction for aspect coding.

In this qualitative study, use the general  question: "Do you feel your needs are being met by TARGET ACTIVITY/BEHAVIOUR?"; or use a more narrow question to ask whether a specific universal need is met: "Do you feel you have a connection with the people at work?". The latter question is an example to assess whether "relatedness", one of the universal needs according to SDT, is met. 





## Coding Qualitative Data

Expressions that demonstrate or imply that needs are satisfied or not satisfied by the activity or behaviour of interest, for example: "I feel like I can make a lot of inputs to deciding how my job gets done", "People at work do not care about me", and "Most days I feel a sense of accomplishment from working". 

Self-Determination Theory (SDT) (Deci & Ryan, 1985) regards relatedness, autonomy, and competence as the three basic human needs. Therefore, expressions that indicate that autonomy and competence are regarded as important individual needs should be coded as dct:need_79n2fh4r and as, respectively, dct:autonomy_73dnt5zx and dct:capacity_73dnt602.

In a similar fashion, other expressions of needs may be given the coding dct:need_79n2fh4r and of another dct, e.g. dct:injunctiveNorms_73dnt5zj, if the participant expresses that approval of people around him/her of his/her behaviour is regarded as an important individual need.

