---
format: html
subtitle: 'UCID: perceivedNorms_73dnt5zq'
title: Perceived norms
toc: true
---

## Definition

Perceived social pressure to perform (or not to perform) the target behavior.

## Developing Measurement Instruments

Use likert scales that measure both perceived social approval and perceived behavior of important social referents in general. It is important that no specific individuals are referenced, but that the items do refer to individuals that are similar, important or seen as important to follow. Note that the behavior in these items must always be the target behavior.

The example items in the 2010 RAA book are ‘Most people who are important to me think I should TARGET BEHAVIOR.’ with anchors ‘False’ vs ‘True’; ‘Most people whose opinions I value would … of my TARGET BEHAVIOR’ with anchors ‘Disapprove’ vs ‘Approve’; ‘Most people I respect and admire will TARGET BEHAVIOR.’ with anchors ‘Unlikely’ vs ‘Likely’; and ‘How many people like you TARGET BEHAVIOR?’ with anchors ‘Nobody’ vs ‘Everybody’.


## Coding Measurement Instruments

Questionnaires that measure both perceived social approval and perceived behavior of important social referents in general. It is important that no specific individuals are referenced, but that the items do refer to individuals that are similar, important or seen as important to follow. Note that the behavior in these items must always be the target behavior.


## Eliciting Construct Content (Qualitative Research)

Conduct a qualitative study where participants are interviewed, and the interviews are either recorded and transcribed, or notes are kept. These sources are then coded using the instruction for aspect coding.

In this qualitative study, use the introduction ‘When it comes to TARGET BEHAVIOR, there might be individuals or groups who would think you should or should not perform this behavior.’, and then ask these questions: ‘Please list any individuals or groups who would approve or think you should TARGET BEHAVIOR’; ‘Please list any individuals or groups who would disapprove or think you should not TARGET BEHAVIOR’; ‘Sometimes, when we are not sure what to do, we look to see what others are doing. Please list the individuals or groups who are most likely to TARGET BEHAVIOR’; and ‘Please list the individuals or groups who are least likely to TARGET BEHAVIOR’.


## Coding Qualitative Data

Expressions that refer to social pressure in general. However, expressions about perceived behavior of others are coded as dct:perceivedNorm_descriptive_73bg61tx and expressions about perceived (dis)approval of others are coded as dct:perceivedNorm_injunctive_73bg2wm7.


