project:
  type: website
  output-dir: docs
  pre-render: generate_construct_pages.py
  resources: 
    - "img/*.*"
    - "img/logo/*.*"
    - "css/*.*"
    - "js/*.*"
    - "repo/overview/search_index.json"

website:
  site-url: https://gerritsxd.github.io/core2
  title: "COMMS Repository Template: CoRe"
  navbar:
    background: "#666666"
    foreground: "#BBBBBB"
    left:
      - repo/index.qmd
      - posts/index.qmd

format:
  html:
    theme: cosmo
    css: /styles.css
    toc: true

execute:
  freeze: false
